
services:
    app:
        container_name: ${APP_NAME}-${APP_ENV}
        image: "cr.codeboys.pt/geral/dockerbuilds:latest"
        working_dir: /app
        user: '${UID}:${WEB_SERVER_GROUP}'
        environment:
            WEB_DOCUMENT_ROOT: "/app/public"
        volumes:
            - "./:/app"
            - "../log-hole:/app/log-hole"
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        depends_on:
            - app_redis
        networks:
            - sail

    app_redis:
        image: redis:7.2.2-alpine
        networks:
            - sail

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
            - "../log-hole:/app/log-hole"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '1'
            SOKETI_METRICS_SERVER_PORT: '9601'
        ports:
            - '${SOKETI_PORT:-6001}:6001'
            - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
        networks:
            - sail
    mailhog:
        image: mailhog/mailhog
        logging:
            driver: 'none'  # disable saving logs
        ports:
            - '${MAIL_PORT}:${MAIL_PORT}' # smtp server
            - '8025:8025' # web ui
        networks:
            - sail

networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    meilisearch_data:
        driver: local
